[project]
name = "module01-docker-terraform"
version = "0.1.0"
description = "module01-docker-terraform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
    "pyarrow>=23.0.0",
]
